package com.syntxr.korediary.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

//val Mountain
//light
val primaryLightMountain = Color(0xFF34618D)
val onPrimaryLightMountain = Color(0xFFFFFFFF)
val primaryContainerLightMountain = Color(0xFFD0E4FF)
val onPrimaryContainerLightMountain = Color(0xFF001D35)
val secondaryLightMountain = Color(0xFF526070)
val onSecondaryLightMountain = Color(0xFFFFFFFF)
val secondaryContainerLightMountain = Color(0xFFD6E4F7)
val onSecondaryContainerLightMountain = Color(0xFF0F1D2A)
val tertiaryLightMountain = Color(0xFF6A5779)
val onTertiaryLightMountain = Color(0xFFFFFFFF)
val tertiaryContainerLightMountain = Color(0xFFF1DAFF)
val onTertiaryContainerLightMountain = Color(0xFF241432)
val errorLightMountain = Color(0xFFBA1A1A)
val onErrorLightMountain = Color(0xFFFFFFFF)
val errorContainerLightMountain = Color(0xFFFFDAD6)
val onErrorContainerLightMountain = Color(0xFF410002)
val backgroundLightMountain = Color(0xFFF8F9FF)
val onBackgroundLightMountain = Color(0xFF191C20)
val surfaceLightMountain = Color(0xFFF8F9FF)
val onSurfaceLightMountain = Color(0xFF191C20)
val surfaceVariantLightMountain = Color(0xFFDFE3EB)
val onSurfaceVariantLightMountain = Color(0xFF42474E)
val outlineLightMountain = Color(0xFF73777F)
val outlineVariantLightMountain = Color(0xFFC2C7CF)
val scrimLightMountain = Color(0xFF000000)
val inverseSurfaceLightMountain = Color(0xFF2D3135)
val inverseOnSurfaceLightMountain = Color(0xFFEFF0F7)
val inversePrimaryLightMountain = Color(0xFF9ECAFC)
val surfaceDimLightMountain = Color(0xFFD8DAE0)
val surfaceBrightLightMountain = Color(0xFFF8F9FF)
val surfaceContainerLowestLightMountain = Color(0xFFFFFFFF)
val surfaceContainerLowLightMountain = Color(0xFFF2F3F9)
val surfaceContainerLightMountain = Color(0xFFECEEF4)
val surfaceContainerHighLightMountain = Color(0xFFE6E8EE)
val surfaceContainerHighestLightMountain = Color(0xFFE1E2E8)

//dark
val primaryDarkMountain = Color(0xFF9ECAFC)
val onPrimaryDarkMountain = Color(0xFF003256)
val primaryContainerDarkMountain = Color(0xFF164974)
val onPrimaryContainerDarkMountain = Color(0xFFD0E4FF)
val secondaryDarkMountain = Color(0xFFBAC8DB)
val onSecondaryDarkMountain = Color(0xFF243140)
val secondaryContainerDarkMountain = Color(0xFF3B4857)
val onSecondaryContainerDarkMountain = Color(0xFFD6E4F7)
val tertiaryDarkMountain = Color(0xFFD5BEE5)
val onTertiaryDarkMountain = Color(0xFF3A2948)
val tertiaryContainerDarkMountain = Color(0xFF514060)
val onTertiaryContainerDarkMountain = Color(0xFFF1DAFF)
val errorDarkMountain = Color(0xFFFFB4AB)
val onErrorDarkMountain = Color(0xFF690005)
val errorContainerDarkMountain = Color(0xFF93000A)
val onErrorContainerDarkMountain = Color(0xFFFFDAD6)
val backgroundDarkMountain = Color(0xFF101418)
val onBackgroundDarkMountain = Color(0xFFE1E2E8)
val surfaceDarkMountain = Color(0xFF101418)
val onSurfaceDarkMountain = Color(0xFFE1E2E8)
val surfaceVariantDarkMountain = Color(0xFF42474E)
val onSurfaceVariantDarkMountain = Color(0xFFC2C7CF)
val outlineDarkMountain = Color(0xFF8C9199)
val outlineVariantDarkMountain = Color(0xFF42474E)
val scrimDarkMountain = Color(0xFF000000)
val inverseSurfaceDarkMountain = Color(0xFFE1E2E8)
val inverseOnSurfaceDarkMountain = Color(0xFF2D3135)
val inversePrimaryDarkMountain = Color(0xFF34618D)
val surfaceDimDarkMountain = Color(0xFF101418)
val surfaceBrightDarkMountain = Color(0xFF36393E)
val surfaceContainerLowestDarkMountain = Color(0xFF0B0E12)
val surfaceContainerLowDarkMountain = Color(0xFF191C20)
val surfaceContainerDarkMountain = Color(0xFF1D2024)
val surfaceContainerHighDarkMountain = Color(0xFF272A2F)
val surfaceContainerHighestDarkMountain = Color(0xFF32353A)



//val Sakura
//light
val primaryLightSakura = Color(0xFF8F4A4D)
val onPrimaryLightSakura = Color(0xFFFFFFFF)
val primaryContainerLightSakura = Color(0xFFFFDADA)
val onPrimaryContainerLightSakura = Color(0xFF3B080E)
val secondaryLightSakura = Color(0xFF765657)
val onSecondaryLightSakura = Color(0xFFFFFFFF)
val secondaryContainerLightSakura = Color(0xFFFFDADA)
val onSecondaryContainerLightSakura = Color(0xFF2C1516)
val tertiaryLightSakura = Color(0xFF755A2F)
val onTertiaryLightSakura = Color(0xFFFFFFFF)
val tertiaryContainerLightSakura = Color(0xFFFFDDB0)
val onTertiaryContainerLightSakura = Color(0xFF291800)
val errorLightSakura = Color(0xFFBA1A1A)
val onErrorLightSakura = Color(0xFFFFFFFF)
val errorContainerLightSakura = Color(0xFFFFDAD6)
val onErrorContainerLightSakura = Color(0xFF410002)
val backgroundLightSakura = Color(0xFFFFF8F7)
val onBackgroundLightSakura = Color(0xFF221919)
val surfaceLightSakura = Color(0xFFFFF8F7)
val onSurfaceLightSakura = Color(0xFF221919)
val surfaceVariantLightSakura = Color(0xFFF4DDDD)
val onSurfaceVariantLightSakura = Color(0xFF524343)
val outlineLightSakura = Color(0xFF857373)
val outlineVariantLightSakura = Color(0xFFD7C1C1)
val scrimLightSakura = Color(0xFF000000)
val inverseSurfaceLightSakura = Color(0xFF382E2E)
val inverseOnSurfaceLightSakura = Color(0xFFFFEDEC)
val inversePrimaryLightSakura = Color(0xFFFFB3B4)
val surfaceDimLightSakura = Color(0xFFE8D6D6)
val surfaceBrightLightSakura = Color(0xFFFFF8F7)
val surfaceContainerLowestLightSakura = Color(0xFFFFFFFF)
val surfaceContainerLowLightSakura = Color(0xFFFFF0F0)
val surfaceContainerLightSakura = Color(0xFFFCEAE9)
val surfaceContainerHighLightSakura = Color(0xFFF6E4E4)
val surfaceContainerHighestLightSakura = Color(0xFFF0DEDE)

// dark
val primaryDarkSakura = Color(0xFFFFB3B4)
val onPrimaryDarkSakura = Color(0xFF561D22)
val primaryContainerDarkSakura = Color(0xFF733337)
val onPrimaryContainerDarkSakura = Color(0xFFFFDADA)
val secondaryDarkSakura = Color(0xFFE6BDBD)
val onSecondaryDarkSakura = Color(0xFF44292A)
val secondaryContainerDarkSakura = Color(0xFF5D3F40)
val onSecondaryContainerDarkSakura = Color(0xFFFFDADA)
val tertiaryDarkSakura = Color(0xFFE6C18D)
val onTertiaryDarkSakura = Color(0xFF422C05)
val tertiaryContainerDarkSakura = Color(0xFF5B421A)
val onTertiaryContainerDarkSakura = Color(0xFFFFDDB0)
val errorDarkSakura = Color(0xFFFFB4AB)
val onErrorDarkSakura = Color(0xFF690005)
val errorContainerDarkSakura = Color(0xFF93000A)
val onErrorContainerDarkSakura = Color(0xFFFFDAD6)
val backgroundDarkSakura = Color(0xFF1A1111)
val onBackgroundDarkSakura = Color(0xFFF0DEDE)
val surfaceDarkSakura = Color(0xFF1A1111)
val onSurfaceDarkSakura = Color(0xFFF0DEDE)
val surfaceVariantDarkSakura = Color(0xFF524343)
val onSurfaceVariantDarkSakura = Color(0xFFD7C1C1)
val outlineDarkSakura = Color(0xFF9F8C8C)
val outlineVariantDarkSakura = Color(0xFF524343)
val scrimDarkSakura = Color(0xFF000000)
val inverseSurfaceDarkSakura = Color(0xFFF0DEDE)
val inverseOnSurfaceDarkSakura = Color(0xFF382E2E)
val inversePrimaryDarkSakura = Color(0xFF8F4A4D)
val surfaceDimDarkSakura = Color(0xFF1A1111)
val surfaceBrightDarkSakura = Color(0xFF413737)
val surfaceContainerLowestDarkSakura = Color(0xFF140C0C)
val surfaceContainerLowDarkSakura = Color(0xFF221919)
val surfaceContainerDarkSakura = Color(0xFF271D1D)
val surfaceContainerHighDarkSakura = Color(0xFF322828)
val surfaceContainerHighestDarkSakura = Color(0xFF3D3232)





